loongarch64
loongarch64-archive/libaio pull request #1
Opened 2021-06-07 10:52 UTC by renyehui

添加loongarch64架构

2021-06-07 13:19 UTC, yetist requested changes

2021-06-07 13:19 UTC, yetist commented on harness/cases/16.t
> +#elif defined(__aarch64__) || defined(__riscv) || defined(__loongarch64__)
没有`__loongarch64__`，应该是 `__loongarch64`

2021-06-07 13:19 UTC, yetist commented on src/libaio.h
> +      (defined(__loongarch64__)) || \
没有`__loongarch64__`，应该是 `__loongarch64`

2021-06-07 13:19 UTC, yetist commented on src/syscall.h
> +#elif defined(__loongarch64__)
没有`__loongarch64__`，应该是 `__loongarch64`

2021-06-08 01:51 UTC, renyehui commented on src/syscall.h
> +#elif defined(__loongarch64__)
好的，那这个请求用关闭吗？我按您的要求把上面三个文件修改后再重新提交请求

2021-06-08 01:58 UTC, yetist commented on src/syscall.h
> +#elif defined(__loongarch64__)
不用关闭，继续commit，然后push就行。

2021-06-08 02:16 UTC, renyehui commented on src/syscall.h
> +#elif defined(__loongarch64__)
好的

2021-06-08 02:52 UTC, renyehui commented on src/syscall.h
> +#elif defined(__loongarch64__)
您好，已经重新push，之前没有做过上游提交，有很多事还要多向您请教，在咱们loongarch64组织上合并后，提交上游的话是您这边提交还是我们自己去提交？

2021-06-08 03:40 UTC, yetist commented
使用 `git rebase -i master` 重新修正一下历史，把2次提交合并为一次，再强制推送上来。

2021-06-08 07:28 UTC, cnmushiba commented on harness/cases/16.t
>  /* arm64 and riscv do not implement eventfd, only eventfd2 */
注释代码统一一下

2021-06-08 07:28 UTC, cnmushiba commented on src/libaio.h
> +      (defined(__loongarch64)) || \
外层括号应该不用了吧？

2021-06-08 09:15 UTC, renyehui commented on harness/cases/16.t
>  /* arm64 and riscv do not implement eventfd, only eventfd2 */
好的，我把注释改一下

2021-06-08 09:17 UTC, renyehui commented on src/libaio.h
> +      (defined(__loongarch64)) || \
好的

2021-06-08 09:46 UTC, xen0n requested changes

2021-06-08 09:46 UTC, xen0n commented on harness/cases/16.t
> +/* arm64 riscv and loongarch64 do not implement eventfd, only eventfd2 */
1. 请按字母顺序排列
2. 标点符号用法，应该加一个逗号，类似这样：`arm64, loongarch64 and riscv`

2021-06-08 09:46 UTC, xen0n commented on src/syscall-loongarch64.h
> +#define __NR_io_getevents 4
LA 内核的系统调用号和 generic 一致，这个文件压根不需要用到

2021-06-08 09:46 UTC, xen0n commented on src/syscall.h
> +#include "syscall-loongarch64.h"
这个更改也是不需要的，LA 的判断加到下面 `syscall-generic.h` 的那个块就好了

2021-06-08 09:47 UTC, xen0n commented on harness/cases/16.t
> +/* arm64 riscv and loongarch64 do not implement eventfd, only eventfd2 */
注意到这里的几个架构都是比较新的 port，注释也可以调整一下，类似 `these recent architectures do not implement ...` 这样。

2021-06-08 09:51 UTC, renyehui commented on harness/cases/16.t
> +/* arm64 riscv and loongarch64 do not implement eventfd, only eventfd2 */
好的

2021-06-08 09:52 UTC, renyehui commented on src/syscall-loongarch64.h
> +#define __NR_io_getevents 4
您的意思是把这个文件去掉？

2021-06-08 09:56 UTC, renyehui commented on src/syscall.h
> +#include "syscall-loongarch64.h"
那我把syscall.h添加的这两行去掉，您刚刚说LA 内核的系统调用号和 generic 一致，syscall-generic.h这个文件我用默认的就可以吗？用改动吗？

2021-06-08 09:56 UTC, xen0n commented on src/syscall-loongarch64.h
> +#define __NR_io_getevents 4
对的，generic 的东西不需要重复

2021-06-08 09:58 UTC, xen0n commented on src/syscall.h
> +#include "syscall-loongarch64.h"
不需要改动，只改这里就好了

2021-06-08 09:59 UTC, xen0n commented on src/syscall.h
> +#include "syscall-loongarch64.h"
啊，LA32 应该也是跟随 generic，这边改成 `__loongarch__`，所有不涉及 32/64 位的地方，对 LA 预处理符号的判断都应该使用 `__loongarch__` 而非 `__loongarch64` 免得以后还要再搞一遍

2021-06-09 01:32 UTC, renyehui commented on src/syscall.h
> +#include "syscall-loongarch64.h"
好的，那我需要将__loongarch64都改成__loongarch__是吧？

2021-06-09 01:51 UTC, renyehui commented on src/syscall.h
> +#include "syscall-loongarch64.h"
您说的LA 内核的系统调用号和 generic 一致，那改动syscall.h文件，在以下行
#elif defined(__aarch64__) || defined(__riscv)
#include "syscall-generic.h"
是不是要加个loongarch，即：
#elif defined(__aarch64__) || defined(__riscv) || defined(__loongarch__)
#include "syscall-generic.h"

2021-06-09 03:02 UTC, renyehui commented on src/syscall.h
> +#include "syscall-loongarch64.h"
还要请问一下您，您这边审核通过，合并到咱们这个仓库的主分支后，如何上传到上游，是我们来操作还是您这边来操作？

2021-06-09 03:28 UTC, xen0n commented on src/libaio.h
> +      defined(__loongarch__) || \
这个地方有问题，这个地方周围判断的实际上是“小端 64 位”，此处应该是 `__loongarch64`。

实际上，如果不考虑非 GCC 编译器，这里不加也罢，注意最底下有一个判断 `__GNUC__` 的分句，LA64 已经满足了。此处建议改 `__loongarch64`，然后上面 `little endian, 32 bits` 也加一下 `__loongarch32` 的判断。

2021-06-09 03:28 UTC, xen0n commented on src/syscall.h
> +#elif defined(__aarch64__) || defined(__riscv) || defined(__loongarch__)
建议按字母顺序排序，加到 RV 前面。

2021-06-09 03:29 UTC, xen0n commented on harness/cases/16.t
> +#elif defined(__aarch64__) || defined(__riscv) || defined(__loongarch__)
加到 RV 前面

2021-06-09 04:41 UTC, yetist commented on src/libaio.h
> +      defined(__loongarch__) || \
目前工具链还不支持32位，后面有没有__loongarch32还真不好说。联合 __loongarch__和 __loongarch64来做判断至少目前看起来是靠谱的。

2021-06-09 05:49 UTC, xen0n commented on src/libaio.h
> +      defined(__loongarch__) || \
我建议是先加着，因为如果确定LA在Linux只做一个ABI的话，放着也没关系，以后再删也不迟；如果以后会有multilib的需求，只要有可能出LA32 ABI，那这个符号名字肯定叫 `__loongarch32`，现在这么写就正好。

2021-06-09 05:50 UTC, xen0n commented on harness/cases/16.t
> +#elif defined(__aarch64__) || defined(__loongarch__) || defined(__riscv)
行末尾多了个空格，删掉

2021-06-09 05:50 UTC, xen0n commented on src/syscall.h
> +#elif defined(__aarch64__) || defined(__loongarch__) || defined(__riscv)
同上

2021-06-09 06:12 UTC, renyehui commented on src/syscall.h
> +#elif defined(__aarch64__) || defined(__loongarch__) || defined(__riscv)
已重新上传，您看看，如果没问题我再和历史

2021-06-09 06:15 UTC, xen0n reviewed
看上去没啥问题了，我没测试过，机器还没弄好，有测试条件的测一下

Squash 同时 commit message 也改一下，目前不符合项目惯例。建议改成“Add support for LoongArch” 即可。（本次适配的代码部分（非 RPM spec）同时适用 LA32 和 LA64）

2021-06-09 07:14 UTC, yetist commented on src/syscall.h
> +#include "syscall-loongarch64.h"
@renyehui 

我们尊重和感谢每个愿意为LoongArch生态作出贡献的开发者，向上游发起合并请求或提交补丁仍然由原始作者（就是您）来完成，我们在这里只是集中进行一轮review工作，以保证合入上游的代码质量。再次感谢您的贡献和参与。

2021-06-09 08:37 UTC, renyehui commented on src/syscall.h
> +#include "syscall-loongarch64.h"
您看像这个仓库，源码地址为https://pagure.io/libaio，这个我应该如何向上游发起合并

2021-06-09 10:20 UTC, xen0n commented on src/syscall.h
> +#include "syscall-loongarch64.h"
找邮件列表发邮件

类似的问题以后建议不要问，自己在README、项目官网这种地方看

2021-06-09 10:21 UTC, xen0n approved these changes
LGTM but I can't test at the moment

2021-06-10 01:25 UTC, renyehui commented
目前没什么问题，我可以向上游发起合并请求吗？

2021-06-10 01:51 UTC, yetist commented
> 目前没什么问题，我可以向上游发起合并请求吗？

等review完成，分支合并之后，你再发起。

2021-06-10 01:56 UTC, yetist approved these changes
`make partcheck` 测试结果：
```
Pass: 17  Fail: 0  Skip: 1
Test run complete at 2021年 06月 10日 星期四 09:53:51 CST
```

2021-06-10 02:00 UTC, yetist commented
@renyehui 

目前已有2人同意合并，再找一个人给下review意见，如果有3+人同意，我们就进行合并，然后你就可以向上游发起合并/提交补丁了。

2021-06-10 02:14 UTC, renyehui commented
好的，@cnmushiba这位老师能给下review意见吗？

2021-06-10 02:28 UTC, renyehui commented on harness/cases/16.t
>  /* arm64 and riscv do not implement eventfd, only eventfd2 */
您好，能给下review意见吗？可以的话我这边需要进行一下合并

2021-06-10 02:48 UTC, cnmushiba commented on src/libaio.h
> +    defined(__cris__) || defined(__loongarch32) || \
这儿的应该是无序的，我认为不改动riscv那一行，新添加一行比较好，

2021-06-10 02:48 UTC, cnmushiba commented on src/libaio.h
> +      defined(__loongarch64) || \
我觉得加到riscv之后一行，应该好一些，对于这种无序的

2021-06-10 02:50 UTC, cnmushiba commented
> 好的，@cnmushiba这位老师能给下review意见吗？



> 好的，@cnmushiba这位老师能给下review意见吗？

下次直接@就可以了，称谓就免了

2021-06-10 02:50 UTC, cnmushiba commented
make check通过，有些测试项需要root权限check。

2021-06-10 02:53 UTC, Angie-JA-Dou commented on src/libaio.h
> +    defined(__cris__) || defined(__loongarch32) || \
赞同新添加一行， 这样能明显看出添加修改的内容，或者不另起一行，只是添加到同一行。

2021-06-10 03:01 UTC, Angie-JA-Dou approved these changes

2021-06-10 03:16 UTC, xen0n commented on src/libaio.h
> +      defined(__loongarch64) || \
也没有特别无序，最近邻的几组是字母顺序的（alpha aarch64 riscv）

2021-06-10 03:17 UTC, xen0n commented on src/libaio.h
> +      defined(__loongarch64) || \
正常应该先来一个整理顺序的纯重构提交，然后按字母顺序加在正确位置

2021-06-10 03:26 UTC, yetist commented
@cnmushiba @xen0n @Angie-JA-Dou

各位reviewer，可以根据自身情况，使用`git commit --amend` 来增加Reviewed-by信息，以体现各位reviewer的工作成果。

2021-06-10 05:11 UTC, renyehui commented
@yetist 目前已有三人同意，这个合并的操作是由您来，还是我这边来？

2021-06-10 06:08 UTC, merged

2021-06-10 06:11 UTC, yetist commented
非常感谢，PR已经合并，可以将 `la64/master` 的修改提交到上游了。

2021-06-10 07:55 UTC, cnmushiba commented on src/libaio.h
> +      defined(__loongarch64) || \
> 也没有特别无序，最近邻的几组是字母顺序的（alpha aarch64 riscv）

我感觉有序的应该是aarch64 alpha riscv:stuck_out_tongue_closed_eyes:

2021-06-11 06:01 UTC, renyehui commented
好的，有一点想咨询一下，目前5000还没有正式开放，可以上传这个修改的源码吗？还有就是上游要求做一个“make partcheck”在5000上测试的结果可以发给上游吗？

2021-06-11 06:16 UTC, xen0n commented
这边的修改由于涉及系统调用，建议是等 Linux 的 LA 移植至少先推出来一版，再去推进会好一些。否则外面的人不知道细节，可能造成反复，甚至造成错误逻辑进到某个稳定版。

2021-06-11 07:39 UTC, yetist commented
> 好的，有一点想咨询一下，目前5000还没有正式开放，可以上传这个修改的源码吗？还有就是上游要求做一个“make partcheck”在5000上测试的结果可以发给上游吗？

可以发给上游，应该要发完整的make partcheck的log。这几个系统调用号是不会变化的，我觉得可以尝试向上游推。

2021-06-11 08:20 UTC, renyehui commented
好的，谢谢

2021-06-25 14:25 UTC, yetist commented
向上游推送的进展如何了？

2021-06-28 08:23 UTC, renyehui commented
已经向上游提供了测试数据，上游回复测试数据没问题，就是不能证明是在loongarch上执行的，所以我们用readelf -h libaio.so获取了一些证明信息，已经上传，等待回复。

2022-03-29 03:34 UTC, yetist commented
0.3.113 版本发布
```
%changelog
* Mon Mar 28 2022 Jeff Moyer <jmoyer@redhat.com> - 0.3.113-1
- Fix padding in vector and sockaddr structures on 32 bit (Brett Holman)
- Add a test case for missed poll events (Eric Biggers)
- Add loongarch support (Yehui Ren)
- man page cleanup and fixes (Guillem Jover)
- assorted test harness fixess (Guillem Jover, Jeff Moyer)
```
https://pagure.io/libaio/c/1b18bfafc6a2f7b9fa2c6be77a95afed8b7be448?branch=master

2022-03-30 09:35 UTC, yetist commented
项目已存档：https://github.com/loongarch64-archive/libaio